create database online_store;
use online_store;
create table customers (
	customer_id int primary key auto_increment,
    name varchar(100) not null,
    city varchar(100)
);
create table Products(
	product_id int primary key auto_increment,
    name varchar(100) not null,
    category varchar(50),
    price decimal(10,2) not null
);


create table orders(
	order_id int primary key auto_increment,
    customer_id int,
    order_date date,
    foreign key (customer_id) references customers(customer_id)
);

create table order_items(
	order_id int,
    product_id int,
    quantity int not null,
    primary key(order_id, product_id),
    foreign key (order_id) references orders (order_id),
    foreign key (product_id) references products(product_id)
);

(INSERT INTO Customers (name, city) VALUES 
('Alice Johnson', 'New York'),
('Bob Smith', 'Los Angeles'),
('Charlie Brown', 'Chicago');

-- Insert Products
INSERT INTO Products (name, category, price) VALUES 
('Laptop Pro', 'Electronics', 1200.00),
('Smartphone X', 'Electronics', 800.00),
('Coffee Maker', 'Home', 50.00),
('Desk Lamp', 'Home', 25.00);

-- Insert Orders (must use existing customer_ids)
INSERT INTO Orders (customer_id, order_date) VALUES 
(1, '2023-10-01'),
(2, '2023-10-02'),
(1, '2023-10-03');

-- Insert Order Items (must use existing order_ids and product_ids)
INSERT INTO Order_Items (order_id, product_id, quantity) VALUES 
(1, 1, 1), -- Alice bought a Laptop
(1, 2, 2), -- Alice bought 2 Smartphones
(2, 3, 1), -- Bob bought a Coffee Maker
(3, 1, 1); -- Alice bought another Laptop

INSERT INTO Customers (name, city) VALUES 
('Emily Davis', 'New York'),
('Michael Wilson', 'Chicago'),
('Sophia Martinez', 'Philadelphia'),
('James Anderson', 'San Antonio'),
('Olivia Taylor', 'San Antonio'),
('Robert Thomas', 'San Antonio'),
('Isabella Garcia', 'Los Angeles'),
('William Moore', 'Chicago'),
('Mia Young', 'Dallas'),
('David Lee', 'Philadelphia');

INSERT INTO Products (name, category, price) VALUES 
('Wireless Mouse', 'Office', 25.99),
('Mechanical Keyboard', 'Office', 89.99),
('Monitor 24"', 'Electronics', 150.00),
('USB-C Cable', 'Electronics', 15.00),
('Yoga Mat', 'Fitness', 30.00),
('Dumbbell Set', 'Fitness', 45.00),
('Air Fryer', 'Kitchen', 120.00),
('Blender', 'Kitchen', 65.00),
('Office Chair', 'Office', 200.00),
('Table Lamp', 'Home', 35.00);

INSERT INTO Orders (customer_id, order_date) VALUES 
(5, '2023-10-09'),
(11, '2023-10-10'),
(4, '2023-10-11'),
(4, '2023-10-12'),
(13, '2023-10-13'),
(13, '2023-10-14'),
(4, '2023-10-15'),
(10, '2023-10-16'),
(5, '2023-10-17'),
(12, '2023-10-18');

INSERT INTO Order_Items (order_id, product_id, quantity) VALUES 
(4, 5, 1),
(5, 8, 2),
(6, 10, 1),
(7, 2, 1),
(8, 7, 2),
(9, 9, 2),
(10, 4, 1),
(11, 4, 1),
(12, 10, 1),
(13, 2, 3),
(4, 8, 1),
(5, 6, 2);



select sum(quantity) as total_quantity, p.name from order_items as oi
 join products as p on oi.product_id = p.product_id 
 group by oi.product_id order by total_quantity desc;

/*most valuable customer based on number of orders ordered by customer*/  
select count(o.customer_id) as no_of_Orders , o.customer_id, c.name from orders as o
join customers as c on o.customer_id = c.customer_id 
group by o.customer_id order by no_of_Orders desc;

/* Most valuable customer based on spent the money most*/
Select 
    c.customer_id,
    c.name as customer_name,
    SUM(oi.quantity * p.price) AS total_spent
from Customers c
JOIN Orders o on c.customer_id = o.customer_id
JOIN Order_Items oi on o.order_id = oi.order_id
JOIN Products p on oi.product_id = p.product_id
GROUP BY c.customer_id, c.name
ORDER BY total_spent DESC;


/*Montly revenue Calculation total reveue generated each month*/

SELECT 
    DATE_FORMAT(o.date, '%Y-%m') AS month,
    SUM(oi.quantity * p.price) AS monthly_revenue
FROM Orders o
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
GROUP BY month
ORDER BY month;

/*Category wise Sales analysis revenue generated by each product category*/

SELECT 
    p.category,
    SUM(oi.quantity) AS total_units_sold,
    SUM(oi.quantity * p.price) AS total_revenue
FROM Order_Items oi
JOIN Products p ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;

/*Detect inactive Customers*/
SELECT 
    c.customer_id,
    c.name,
    c.city
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;




select * from orders; 





